review_fixture_surveys <- function(root) {
  dina_write_yaml(list(sources = list(list(id = "surveys-cepal", family = "surveys", country = "ARG", method = "manual",
    canonical = "input_data/surveys_CEPAL/*/*.dta", inbox = "input_data/_new/surveys/*"))), file.path(root, "config", "sources.yml"))
  current <- file.path(root, "input_data", "surveys_CEPAL", "ARG", "ARG_2000N.dta")
  incoming <- file.path(root, "input_data", "_new", "surveys", "ARG_2000N.dta")
  dir.create(dirname(current), recursive = TRUE)
  dir.create(dirname(incoming), recursive = TRUE)
  data <- data.frame(`_fep` = c(10, 20), edad = c(30, 10), id_hogar = c(1, 2), check.names = FALSE)
  haven::write_dta(data, current)
  data[["_fep"]] <- c(20, 30)
  haven::write_dta(data, incoming)
  population <- file.path(root, "input_data", "wid", "population_total_adult_npopul.dta")
  dir.create(dirname(population), recursive = TRUE)
  haven::write_dta(data.frame(country = "Argentina", year = 2000L, totalpop = 1000, adultpop = 800), population)
  list(current = current, incoming = incoming)
}

test_that("keyed comparisons detect offsetting revisions and preserve observation identity", {
  source_cli_for_tests()
  old <- data.frame(country = "ARG", year = 2000:2001, variable = "income", value = c(100, 200))
  new <- old
  new$value <- c(110, 190)
  rows <- dina_review_compare(old, new, c("country", "year", "variable"), "value")
  expect_equal(rows$result, c("revised", "revised"))
  expect_equal(rows$difference, c(10, -10))
  expect_equal(rows$variable, rep("income", 2))
  expect_equal(rows$measure, rep("value", 2))
  expect_error(dina_review_compare(old, rbind(new, new[1, ]), c("country", "year"), "value"), "duplicated")
  new$year[1] <- NA
  expect_error(dina_review_compare(old, new, c("country", "year"), "value"), "missing")
})

test_that("comparison distinguishes new observations, missing values and invalid numbers", {
  source_cli_for_tests()
  old <- data.frame(year = 2000:2002, value = c(0, 200, 300))
  new <- data.frame(year = 2000:2003, value = c(10, NA, Inf, 400))
  rows <- dina_review_compare(old, new, "year", "value")
  expect_equal(rows$result, c("revised", "value missing", "nonfinite value", "new observation"))
  expect_true(is.na(rows$percent[1]))
  expect_equal(dina_review_compare(old, old, "year", "value")$result, rep("unchanged", 3))
  expect_error(dina_review_compare(old, data.frame(year = 2000L, value = "bad"), "year", "value"), "nonnumeric")
})

test_that("explore is nonmutating and include accepts and restores the exact survey family", {
  skip_if_not_installed("haven")
  source_cli_for_tests()
  root <- mini_repo()
  files <- review_fixture_surveys(root)
  original <- dina_hash_file(files$current)
  result <- run_dina_cli(c("sources", "explore", "surveys"), root)
  expect_equal(result$status, 0L)
  expect_match(result$output, "1\\. Coverage")
  expect_match(result$output, "2\\. Value changes")
  expect_match(result$output, "3\\. Problems")
  expect_match(result$output, "revisions")
  expect_false(grepl("dry-run", result$output, fixed = TRUE))
  expect_equal(dina_hash_file(files$current), original)
  expect_false(dir.exists(file.path(root, "output", "run_logs")))
  expect_equal(dina_review_read(root, "surveys")$status, "all_good")
  before <- dina_review_recommendation(root)
  expect_equal(before$proposal$command, "dina sources include surveys")
  declined <- run_dina_cli(c("sources", "include", "surveys"), root)
  expect_equal(declined$status, 0L)
  expect_match(declined$output, "No files changed")
  expect_equal(dina_hash_file(files$current), original)
  accepted <- run_dina_cli(c("sources", "include", "surveys", "--confirm"), root)
  expect_equal(accepted$status, 0L)
  expect_match(accepted$output, "Family included")
  expect_equal(dina_hash_file(files$current), dina_hash_file(files$incoming))
  expect_equal(dina_review_read(root, "surveys")$status, "included")
  expect_true(is.null(dina_review_recommendation(root)))
  confirmation <- dina_review_read(root, "surveys")$confirmation
  restored <- run_dina_cli(c("sources", "include", "surveys", "--restore", confirmation), root)
  expect_equal(restored$status, 0L)
  expect_equal(dina_hash_file(files$current), original)
  expect_equal(dina_review_read(root, "surveys")$status, "restored")
})

test_that("changed baseline, configuration or candidate invalidates a saved review", {
  skip_if_not_installed("haven")
  source_cli_for_tests()
  root <- mini_repo()
  files <- review_fixture_surveys(root)
  expect_equal(run_dina_cli(c("sources", "explore", "surveys"), root)$status, 0L)
  record <- dina_review_read(root, "surveys")
  original <- readBin(files$current, "raw", n = file.info(files$current)$size)
  writeLines("changed baseline", files$current)
  expect_error(dina_review_include(root, "surveys", list(confirm = TRUE)), "changed")
  writeBin(original, files$current)
  config <- file.path(root, "config", "dina.yml")
  original_config <- readLines(config)
  writeLines(c(original_config, "# changed"), config)
  expect_error(dina_review_include(root, "surveys", list(confirm = TRUE)), "changed")
  writeLines(original_config, config)
  plan <- dina_review_table(record, "review_files")
  unlink(plan$from_rel[[1]])
  expect_error(dina_review_include(root, "surveys", list(confirm = TRUE)), "changed")
  expect_equal(dina_hash_file(files$current), digest::digest(original, algo = "sha256", serialize = FALSE))
})

test_that("failed exploration invalidates an earlier usable review", {
  skip_if_not_installed("haven")
  source_cli_for_tests()
  root <- mini_repo()
  files <- review_fixture_surveys(root)
  expect_equal(run_dina_cli(c("sources", "explore", "surveys"), root)$status, 0L)
  unlink(file.path(root, "config", "survey_population_include.yml"))
  expect_error(dina_review_explore(root, "surveys"))
  expect_equal(dina_review_read(root, "surveys")$status, "incomplete")
  expect_error(dina_review_include(root, "surveys", list(confirm = TRUE)), "Explore this family first")
})

test_that("menu chooses a family explicitly and includes only after one confirmation", {
  source_cli_for_tests()
  entries <- dina_command_flatten(dina_command_catalog())
  entry <- Filter(function(x) identical(x$key, "sources-explore-type"), entries)[[1]]
  input <- textConnection("3\n")
  on.exit(close(input), add = TRUE)
  args <- dina_command_collect_args(entry, input = input, is_terminal = TRUE)
  expect_equal(args$args, c("sources", "explore", "surveys"))
  expect_error(dina_review_choose_family(is_terminal = FALSE), "Choose a family")
  skip_if_not_installed("haven")
  root <- mini_repo()
  files <- review_fixture_surveys(root)
  expect_equal(run_dina_cli(c("sources", "explore", "surveys"), root)$status, 0L)
  input2 <- textConnection("1\n")
  on.exit(close(input2), add = TRUE)
  # Yes is the first numbered confirmation action; the default remains No.
  output <- capture.output(dina_review_include(root, "surveys", input = input2, is_terminal = TRUE))
  expect_equal(sum(grepl("Accept this reviewed family", output, fixed = TRUE)), 1L)
  expect_equal(dina_review_read(root, "surveys")$status, "included")
})

test_that("family menu and typed Explore save the same review and cancellation preserves sources", {
  source_cli_for_tests()
  root <- mini_repo()
  files <- review_fixture_surveys(root)
  original <- dina_hash_file(files$current)
  expect_equal(run_dina_cli(c("sources", "explore", "surveys"), root)$status, 0L)
  typed <- dina_review_read(root, "surveys")
  rows <- dina_review_table(typed, "review_values")
  input <- textConnection("2\n4\n2\n5\n")
  on.exit(close(input), add = TRUE)
  output <- capture.output(result <- dina_review_family_menu(root, "surveys", input, TRUE))
  menu <- dina_review_read(root, "surveys")
  expect_equal(dina_review_table(menu, "review_values"), rows)
  expect_equal(menu$status, typed$status)
  expect_equal(result, "back")
  expect_equal(dina_hash_file(files$current), original)
  expect_match(paste(output, collapse = "\n"), "dina sources explore surveys", fixed = TRUE)
  expect_match(paste(output, collapse = "\n"), "No files changed", fixed = TRUE)
  expect_error(dina_cmd_sources(root, c("include", "surveys", "--confirm", "--include-run", typed$run)), "superseded")
})

test_that("failed backup prevents replacement and a partial inclusion is reported accurately", {
  source_cli_for_tests()
  root <- mini_repo()
  files <- review_fixture_surveys(root)
  original <- dina_hash_file(files$current)
  second <- file.path(root, "input_data", "_new", "surveys", "COL_2000N.dta")
  file.copy(files$incoming, second)
  expect_equal(run_dina_cli(c("sources", "explore", "surveys"), root)$status, 0L)
  engine <- dina_review_engine(root, "surveys")
  copy <- engine$survey_pop_copy_path
  engine$survey_pop_copy_path <- function(from, to) {
    if (grepl("/snapshots/original/", to, fixed = TRUE)) "copy_failed" else copy(from, to)
  }
  env <- environment(dina_review_include)
  original_engine <- get("dina_review_engine", env)
  on.exit(assign("dina_review_engine", original_engine, env), add = TRUE)
  assign("dina_review_engine", function(...) engine, env)
  expect_error(dina_review_include(root, "surveys", list(confirm = TRUE)), "Inclusion did not complete")
  record <- dina_review_read(root, "surveys")
  expect_equal(record$status, "inclusion_failed")
  expect_equal(dina_hash_file(files$current), original)
  report <- dina_read_csv_table_or_empty(file.path(record$confirmation, "tables", "promote_report.csv"))
  expect_true("skipped_backup_failed" %in% report$promote_status)
  expect_true("staged" %in% report$promote_status)
  expect_equal(dina_review_recommendation(root)$proposal$command, "dina sources table surveys")
  expect_error(dina_review_include(root, "surveys", list(confirm = TRUE)), "unresolved checks")
})

test_that("unavailable evidence and failed exploration cannot look like a successful review", {
  source_cli_for_tests()
  empty <- data.frame(year = 2000L, value = NA_real_)
  expect_equal(dina_review_compare(empty, empty, "year", "value")$result, "absence unexplained")
  root <- mini_repo()
  files <- review_fixture_surveys(root)
  expect_equal(run_dina_cli(c("sources", "explore", "surveys"), root)$status, 0L)
  dina_review_save(list(family = "surveys", status = "incomplete"), root)
  expect_error(dina_cmd_sources(root, c("table", "surveys")), "latest exploration did not complete")
})

test_that("coverage distinguishes extracted extensions, lost years and retained survey history", {
  source_cli_for_tests()
  old <- data.frame(country = "AAA", year = 2000:2002, value = c(1, 2, 3))
  new <- data.frame(country = "AAA", year = c(2000L, 2001L, 2003L), value = c(1, NA, 4))
  values <- dina_review_compare(old, new, c("country", "year"), "value")
  coverage <- dina_review_coverage(list(), values, "sna")
  expect_equal(coverage$extension_years, "2003")
  expect_equal(coverage$overlap_years, "2000")
  expect_equal(coverage$missing_in_new_years, "2001,2002")
  expect_true("removed observation" %in% values$result)
  survey <- list(outputs = list(year_coverage = data.frame(country = "AAA", canonical_discovered_years = "2000-2002",
    incoming_discovered_years = "2002-2003", selected_years = "2000-2003", blocked_years = "", canonical_discovered_count = 3L, incoming_discovered_count = 2L)))
  coverage <- dina_review_coverage(survey, data.frame(), "surveys")
  expect_equal(coverage$extension_years, "2003")
  expect_equal(coverage$overlap_years, "2002")
  expect_equal(coverage$missing_in_new_years, "")
})

test_that("compact registry preserves complete IDs and includes artifacts owned by WID", {
  source_cli_for_tests()
  root <- mini_repo()
  id <- "a-complete-source-id-longer-than-the-old-column-width"
  dina_write_yaml(list(sources = list(list(id = id, family = "prices", country = "MULTI", method = "wid", integration = "sources_explore_include_wid"),
    list(id = "wid-main", family = "wid", country = "ARG", method = "wid"))), file.path(root, "config", "sources.yml"))
  registry <- dina_source_registry(root, dina_source_resolve_family_filter("wid", root))
  expect_equal(length(registry), 2L)
  output <- capture.output(dina_print_source_registry_view(registry, root))
  expect_match(paste(output, collapse = "\n"), id, fixed = TRUE)
  expect_equal(dina_source_public_family(registry[[1]]), "wid")
})

test_that("dashboard and session guidance agree on each family and unfinished reviews", {
  source_cli_for_tests()
  root <- mini_repo()
  session <- list(task_runs = list())
  for (family in c("sna", "admin", "surveys", "wid")) {
    incoming <- file.path(root, "input_data", "_new", family)
    dir.create(incoming, recursive = TRUE, showWarnings = FALSE)
    writeLines("candidate", file.path(incoming, "source.txt"))
    expect_equal(dina_dashboard_state_fast(session, root)$proposal$command, paste("dina sources explore", family))
    record <- list(family = family, run = "fixture", status = "all_good", reviewed_at = dina_now(), watch = dina_review_watch(incoming))
    dina_review_save(record, root)
    expect_equal(dina_session_state(session, root)$proposal$command, paste("dina sources include", family))
    expect_equal(dina_dashboard_state_fast(session, root)$proposal$command, paste("dina sources include", family))
    record$status <- "blocked"
    dina_review_save(record, root)
    expect_equal(dina_dashboard_state_fast(session, root)$proposal$command, paste("dina sources table", family))
    record$status <- "included"
    dina_review_save(record, root)
    expect_null(dina_review_recommendation(root))
  }
})

test_that("an empty survey workspace explains why no review can be prepared", {
  source_cli_for_tests()
  root <- mini_repo()
  result <- run_dina_cli(c("sources", "explore", "surveys"), root)
  expect_equal(result$status, 1L)
  expect_match(result$output, "No survey files are available to prepare", fixed = TRUE)
  expect_match(result$output, "not checked", fixed = TRUE)
  expect_equal(dina_review_read(root, "surveys")$status, "incomplete")
  expect_error(dina_review_include(root, "surveys", list(confirm = TRUE)), "Explore this family first")
})
